### ISSUE TITLE
Add Endpoint CRD and enhance @http directive to support it

### ISSUE THREAD

**Issue by AleF83** [Soluto/agogos#37]
In some cases to perform REST call more than only URL is needed.
Sometimes some additional details are needed to be added to HTTP request.
It may be`Authorization` header or some required headers like `x-api-client` and etc.

So we need the way to declare this details in gql schema objects.

Continuing conversation with @Yshayy we thought to add endpoint CRD.

This is the definition proposal sample:

```yaml
apiVersion: graphql.gateway/v1alpha
kind: GqlEndpoint
metadata:
  name: user-service-endpoint
spec:
  host: "https://user-service.svc"
  headers:
    - name: "x-api-client"
      value: "graphql"
  auth:
    type: application-only
    authority: "https://login.windows.net/tenantId"
    parameters:
      - name: client_id
        valueFrom:
          secretKeyRef:
            name: user-service-credentials
            key: client_id
      - name: client_secret
        valueFrom:
          secretKeyRef:
            name: user-service-credentials
            key: client_secret
      - name: resource
        value: user-service-resource
```

To integrate this CRD with `@http` directive we can choose several alternatives:
1. Replace argument `url` to `endpoint` (maybe continue to support `url` as optional for in-cluster calls)
2. Endpoint definition will be used in the directive logic in cases there will be match between `url` argument of `@http` directive and `host` parameter of endpoint.

In future we need to refer some more aspects related to perforing http request like retry,
timeout, maybe caching.

**Comment by Yshayy** [comment]
Looks good, in the host I won't add the https:// prefix, might worth adding protocol/type.
I would allow adding target host, can useful for local testing (same schemas, different endpoints).
As for oauth, I would be explicit about oauth2. (can be auth-flow, or something)

**Comment by AleF83** [comment]
Some changes in endpoint definition:
```yaml
apiVersion: graphql.gateway/v1alpha
kind: HttpEndpoint
metadata:
  name: user
  namespace: accounts
spec:
  matchHosts: # optional, automatically matches user.accounts due to name+namespace
  - user.myservice.com
  - user.myservice.com
  host: "https://user-service.svc"
  headers: # optional, adding headers
  - name: "x-api-client"
    value: "graphql"
  auth:
    type: ouath2/client_credentials
    spec:
      authority: "https://login.windows.net/tenantId"
      client_id: "some_client_id"
      client_secret:
          secretKeyRef:
            name: user-service-credentials
            key: client_secret
      resource: "user-service-resource"
```
